spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shop
    username: shop
    password: shop

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true